### ISSUE TITLE
[ENHANCEMENT] Implement the device handlers

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/mao-ctrl#1]
## Overview

We need the device handlers to handle MAO-WFS. So I request the feature to operate devices.

## Purpose

It is necessary for MAO-WFS to operate the correlator and the FG in synchronization.

## Feature

- Device handlers
  - Correlator
  - FG

## Tasks

- [ ] Function to start / halt the correlator and the FG in synchronization
- [ ] Correlator
    - [ ] Function to start / halt the correlation
- [ ] FG
    - [ ] Function to start / halt the digital signal output
    - [ ] Generator of the digital signals to switch

## Note

Nothing.
